from typing import Any, Callable

def relationship(*args: Any, **kwargs: Any) -> Any: ...
def sessionmaker(*args: Any, **kwargs: Any) -> Any: ...
def declarative_base(*args: Any, **kwargs: Any) -> Any: ...

class Session:
    def add(self, instance: Any) -> None: ...
    def add_all(self, instances: Any) -> None: ...
    def commit(self) -> None: ...
    def refresh(self, instance: Any) -> None: ...
    def query(self, *entities: Any) -> Any: ...
    def close(self) -> None: ...

class declarative_base:
    metadata: Any
