from typing import Any, Callable, Optional, Type

# Column must be a class (not a plain function) so Column(Integer, ...) works without arg errors
class Column:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __get__(self, obj: Any, type: Any = None) -> Any: ...

def create_engine(*args: Any, **kwargs: Any) -> Any: ...
def text(*args: Any, **kwargs: Any) -> Any: ...
def Index(*args: Any, **kwargs: Any) -> Any: ...
def Table(*args: Any, **kwargs: Any) -> Any: ...
def MetaData(*args: Any, **kwargs: Any) -> Any: ...
def select(*args: Any, **kwargs: Any) -> Any: ...
def and_(*args: Any, **kwargs: Any) -> Any: ...
def or_(*args: Any, **kwargs: Any) -> Any: ...
def func(*args: Any, **kwargs: Any) -> Any: ...
def event(*args: Any, **kwargs: Any) -> Any: ...

# Type classes — all accept positional args via __class_getitem__ or constructor
class TypeEngine:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class Integer(TypeEngine): ...
class String(TypeEngine):
    def __init__(self, length: Optional[int] = None, *args: Any, **kwargs: Any) -> None: ...
class DateTime(TypeEngine): ...
class Boolean(TypeEngine): ...
class Text(TypeEngine): ...
class Float(TypeEngine): ...
class JSON(TypeEngine): ...
class LargeBinary(TypeEngine): ...
class Numeric(TypeEngine): ...
class Enum(TypeEngine):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

# These were missing — caused "Could not import Date/Time" errors
class Date(TypeEngine): ...
class Time(TypeEngine): ...
class Interval(TypeEngine): ...
class TIMESTAMP(TypeEngine): ...
class ARRAY(TypeEngine):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class ForeignKey:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class UniqueConstraint:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class CheckConstraint:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class PrimaryKeyConstraint:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
