from typing import Any, Callable, Dict, List, Optional, Type, Union

class FastAPI:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_middleware(self, *args: Any, **kwargs: Any) -> None: ...
    def include_router(self, *args: Any, **kwargs: Any) -> None: ...
    def on_event(self, event_type: str) -> Callable[..., Any]: ...
    def mount(self, path: str, app: Any, name: Optional[str] = ...) -> None: ...
    def get(self, path: str, *args: Any, **kwargs: Any) -> Callable[..., Any]: ...
    def post(self, path: str, *args: Any, **kwargs: Any) -> Callable[..., Any]: ...

class APIRouter:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def include_router(self, *args: Any, **kwargs: Any) -> None: ...
    def get(self, path: str, *args: Any, **kwargs: Any) -> Callable[..., Any]: ...
    def post(self, path: str, *args: Any, **kwargs: Any) -> Callable[..., Any]: ...

class HTTPException(Exception):
    def __init__(self, status_code: int, detail: Any = ...) -> None: ...

class status:
    HTTP_200_OK: int
    HTTP_400_BAD_REQUEST: int
    HTTP_401_UNAUTHORIZED: int
    HTTP_404_NOT_FOUND: int

def Depends(dependency: Optional[Callable[..., Any]] = ...) -> Any: ...
def Form(default: Any = ..., *args: Any, **kwargs: Any) -> Any: ...
def File(default: Any = ..., *args: Any, **kwargs: Any) -> Any: ...
def Query(default: Any = ..., *args: Any, **kwargs: Any) -> Any: ...

class UploadFile:
    filename: str
    content_type: Optional[str]
    size: Optional[int]
    async def read(self, size: int = -1) -> bytes: ...
    async def write(self, data: bytes) -> None: ...
    async def seek(self, offset: int) -> None: ...
    async def close(self) -> None: ...
