from typing import Any

def pipeline(*args: Any, **kwargs: Any) -> Any: ...

class AutoTokenizer:
    @classmethod
    def from_pretrained(cls, *args: Any, **kwargs: Any) -> Any: ...

class AutoModel:
    @classmethod
    def from_pretrained(cls, *args: Any, **kwargs: Any) -> Any: ...

class AutoModelForCausalLM:
    @classmethod
    def from_pretrained(cls, *args: Any, **kwargs: Any) -> Any: ...

class AutoModelForTokenClassification:
    @classmethod
    def from_pretrained(cls, *args: Any, **kwargs: Any) -> Any: ...

class AutoModelForSeq2SeqLM:
    @classmethod
    def from_pretrained(cls, *args: Any, **kwargs: Any) -> Any: ...

class BitsAndBytesConfig:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class TrainingArguments:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class Trainer:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def train(self, *args: Any, **kwargs: Any) -> Any: ...
    def predict(self, *args: Any, **kwargs: Any) -> Any: ...
