/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzingRouteImport } from './routes/analyzing'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as HomeRouteImport } from './routes/home'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as LabBookingRouteImport } from './routes/lab-booking'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MedicinesRouteImport } from './routes/medicines'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as SymptomsRouteImport } from './routes/symptoms'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as DoctorAnalyticsRouteImport } from './routes/doctor.analytics'
import { Route as DoctorClinicRouteImport } from './routes/doctor.clinic'
import { Route as DoctorCmeRouteImport } from './routes/doctor.cme'
import { Route as DoctorDashboardRouteImport } from './routes/doctor.dashboard'
import { Route as DoctorMessagesRouteImport } from './routes/doctor.messages'
import { Route as DoctorPatientRouteImport } from './routes/doctor.patient'
import { Route as DoctorPatientsRouteImport } from './routes/doctor.patients'
import { Route as DoctorPrescriptionsRouteImport } from './routes/doctor.prescriptions'
import { Route as DoctorProfileRouteImport } from './routes/doctor.profile'
import { Route as DoctorReferralRouteImport } from './routes/doctor.referral'
import { Route as MedicinesAddRouteImport } from './routes/medicines.add'
import { Route as SymptomsTrendsRouteImport } from './routes/symptoms.trends'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzingRoute = AnalyzingRouteImport.update({
  id: '/analyzing',
  path: '/analyzing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const LabBookingRoute = LabBookingRouteImport.update({
  id: '/lab-booking',
  path: '/lab-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicinesRoute = MedicinesRouteImport.update({
  id: '/medicines',
  path: '/medicines',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SymptomsRoute = SymptomsRouteImport.update({
  id: '/symptoms',
  path: '/symptoms',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/doctor/',
  path: '/doctor/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorAnalyticsRoute = DoctorAnalyticsRouteImport.update({
  id: '/doctor/analytics',
  path: '/doctor/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorClinicRoute = DoctorClinicRouteImport.update({
  id: '/doctor/clinic',
  path: '/doctor/clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorCmeRoute = DoctorCmeRouteImport.update({
  id: '/doctor/cme',
  path: '/doctor/cme',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorDashboardRoute = DoctorDashboardRouteImport.update({
  id: '/doctor/dashboard',
  path: '/doctor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorMessagesRoute = DoctorMessagesRouteImport.update({
  id: '/doctor/messages',
  path: '/doctor/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPatientRoute = DoctorPatientRouteImport.update({
  id: '/doctor/patient',
  path: '/doctor/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/doctor/patients',
  path: '/doctor/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPrescriptionsRoute = DoctorPrescriptionsRouteImport.update({
  id: '/doctor/prescriptions',
  path: '/doctor/prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorProfileRoute = DoctorProfileRouteImport.update({
  id: '/doctor/profile',
  path: '/doctor/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorReferralRoute = DoctorReferralRouteImport.update({
  id: '/doctor/referral',
  path: '/doctor/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicinesAddRoute = MedicinesAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => MedicinesRoute,
} as any)
const SymptomsTrendsRoute = SymptomsTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => SymptomsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyzing': typeof AnalyzingRoute
  '/appointments': typeof AppointmentsRoute
  '/assistant': typeof AssistantRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/emergency': typeof EmergencyRoute
  '/family': typeof FamilyRoute
  '/home': typeof HomeRoute
  '/insurance': typeof InsuranceRoute
  '/lab-booking': typeof LabBookingRoute
  '/login': typeof LoginRoute
  '/medicines': typeof MedicinesRouteWithChildren
  '/pharmacy': typeof PharmacyRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/results': typeof ResultsRoute
  '/symptoms': typeof SymptomsRouteWithChildren
  '/upload': typeof UploadRoute
  '/doctor/analytics': typeof DoctorAnalyticsRoute
  '/doctor/clinic': typeof DoctorClinicRoute
  '/doctor/cme': typeof DoctorCmeRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/messages': typeof DoctorMessagesRoute
  '/doctor/patient': typeof DoctorPatientRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/referral': typeof DoctorReferralRoute
  '/medicines/add': typeof MedicinesAddRoute
  '/symptoms/trends': typeof SymptomsTrendsRoute
  '/doctor/': typeof DoctorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyzing': typeof AnalyzingRoute
  '/appointments': typeof AppointmentsRoute
  '/assistant': typeof AssistantRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/emergency': typeof EmergencyRoute
  '/family': typeof FamilyRoute
  '/home': typeof HomeRoute
  '/insurance': typeof InsuranceRoute
  '/lab-booking': typeof LabBookingRoute
  '/login': typeof LoginRoute
  '/medicines': typeof MedicinesRouteWithChildren
  '/pharmacy': typeof PharmacyRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/results': typeof ResultsRoute
  '/symptoms': typeof SymptomsRouteWithChildren
  '/upload': typeof UploadRoute
  '/doctor/analytics': typeof DoctorAnalyticsRoute
  '/doctor/clinic': typeof DoctorClinicRoute
  '/doctor/cme': typeof DoctorCmeRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/messages': typeof DoctorMessagesRoute
  '/doctor/patient': typeof DoctorPatientRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/referral': typeof DoctorReferralRoute
  '/medicines/add': typeof MedicinesAddRoute
  '/symptoms/trends': typeof SymptomsTrendsRoute
  '/doctor': typeof DoctorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyzing': typeof AnalyzingRoute
  '/appointments': typeof AppointmentsRoute
  '/assistant': typeof AssistantRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/emergency': typeof EmergencyRoute
  '/family': typeof FamilyRoute
  '/home': typeof HomeRoute
  '/insurance': typeof InsuranceRoute
  '/lab-booking': typeof LabBookingRoute
  '/login': typeof LoginRoute
  '/medicines': typeof MedicinesRouteWithChildren
  '/pharmacy': typeof PharmacyRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/results': typeof ResultsRoute
  '/symptoms': typeof SymptomsRouteWithChildren
  '/upload': typeof UploadRoute
  '/doctor/analytics': typeof DoctorAnalyticsRoute
  '/doctor/clinic': typeof DoctorClinicRoute
  '/doctor/cme': typeof DoctorCmeRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/messages': typeof DoctorMessagesRoute
  '/doctor/patient': typeof DoctorPatientRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/referral': typeof DoctorReferralRoute
  '/medicines/add': typeof MedicinesAddRoute
  '/symptoms/trends': typeof SymptomsTrendsRoute
  '/doctor/': typeof DoctorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyzing'
    | '/appointments'
    | '/assistant'
    | '/chat'
    | '/compare'
    | '/emergency'
    | '/family'
    | '/home'
    | '/insurance'
    | '/lab-booking'
    | '/login'
    | '/medicines'
    | '/pharmacy'
    | '/profile'
    | '/reports'
    | '/results'
    | '/symptoms'
    | '/upload'
    | '/doctor/analytics'
    | '/doctor/clinic'
    | '/doctor/cme'
    | '/doctor/dashboard'
    | '/doctor/messages'
    | '/doctor/patient'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/doctor/profile'
    | '/doctor/referral'
    | '/medicines/add'
    | '/symptoms/trends'
    | '/doctor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyzing'
    | '/appointments'
    | '/assistant'
    | '/chat'
    | '/compare'
    | '/emergency'
    | '/family'
    | '/home'
    | '/insurance'
    | '/lab-booking'
    | '/login'
    | '/medicines'
    | '/pharmacy'
    | '/profile'
    | '/reports'
    | '/results'
    | '/symptoms'
    | '/upload'
    | '/doctor/analytics'
    | '/doctor/clinic'
    | '/doctor/cme'
    | '/doctor/dashboard'
    | '/doctor/messages'
    | '/doctor/patient'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/doctor/profile'
    | '/doctor/referral'
    | '/medicines/add'
    | '/symptoms/trends'
    | '/doctor'
  id:
    | '__root__'
    | '/'
    | '/analyzing'
    | '/appointments'
    | '/assistant'
    | '/chat'
    | '/compare'
    | '/emergency'
    | '/family'
    | '/home'
    | '/insurance'
    | '/lab-booking'
    | '/login'
    | '/medicines'
    | '/pharmacy'
    | '/profile'
    | '/reports'
    | '/results'
    | '/symptoms'
    | '/upload'
    | '/doctor/analytics'
    | '/doctor/clinic'
    | '/doctor/cme'
    | '/doctor/dashboard'
    | '/doctor/messages'
    | '/doctor/patient'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/doctor/profile'
    | '/doctor/referral'
    | '/medicines/add'
    | '/symptoms/trends'
    | '/doctor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzingRoute: typeof AnalyzingRoute
  AppointmentsRoute: typeof AppointmentsRoute
  AssistantRoute: typeof AssistantRoute
  ChatRoute: typeof ChatRoute
  CompareRoute: typeof CompareRoute
  EmergencyRoute: typeof EmergencyRoute
  FamilyRoute: typeof FamilyRoute
  HomeRoute: typeof HomeRoute
  InsuranceRoute: typeof InsuranceRoute
  LabBookingRoute: typeof LabBookingRoute
  LoginRoute: typeof LoginRoute
  MedicinesRoute: typeof MedicinesRouteWithChildren
  PharmacyRoute: typeof PharmacyRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  ResultsRoute: typeof ResultsRoute
  SymptomsRoute: typeof SymptomsRouteWithChildren
  UploadRoute: typeof UploadRoute
  DoctorAnalyticsRoute: typeof DoctorAnalyticsRoute
  DoctorClinicRoute: typeof DoctorClinicRoute
  DoctorCmeRoute: typeof DoctorCmeRoute
  DoctorDashboardRoute: typeof DoctorDashboardRoute
  DoctorMessagesRoute: typeof DoctorMessagesRoute
  DoctorPatientRoute: typeof DoctorPatientRoute
  DoctorPatientsRoute: typeof DoctorPatientsRoute
  DoctorPrescriptionsRoute: typeof DoctorPrescriptionsRoute
  DoctorProfileRoute: typeof DoctorProfileRoute
  DoctorReferralRoute: typeof DoctorReferralRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzing': {
      id: '/analyzing'
      path: '/analyzing'
      fullPath: '/analyzing'
      preLoaderRoute: typeof AnalyzingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-booking': {
      id: '/lab-booking'
      path: '/lab-booking'
      fullPath: '/lab-booking'
      preLoaderRoute: typeof LabBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicines': {
      id: '/medicines'
      path: '/medicines'
      fullPath: '/medicines'
      preLoaderRoute: typeof MedicinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symptoms': {
      id: '/symptoms'
      path: '/symptoms'
      fullPath: '/symptoms'
      preLoaderRoute: typeof SymptomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/doctor'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/analytics': {
      id: '/doctor/analytics'
      path: '/doctor/analytics'
      fullPath: '/doctor/analytics'
      preLoaderRoute: typeof DoctorAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/clinic': {
      id: '/doctor/clinic'
      path: '/doctor/clinic'
      fullPath: '/doctor/clinic'
      preLoaderRoute: typeof DoctorClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/cme': {
      id: '/doctor/cme'
      path: '/doctor/cme'
      fullPath: '/doctor/cme'
      preLoaderRoute: typeof DoctorCmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/dashboard': {
      id: '/doctor/dashboard'
      path: '/doctor/dashboard'
      fullPath: '/doctor/dashboard'
      preLoaderRoute: typeof DoctorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/messages': {
      id: '/doctor/messages'
      path: '/doctor/messages'
      fullPath: '/doctor/messages'
      preLoaderRoute: typeof DoctorMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/patient': {
      id: '/doctor/patient'
      path: '/doctor/patient'
      fullPath: '/doctor/patient'
      preLoaderRoute: typeof DoctorPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/doctor/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/prescriptions': {
      id: '/doctor/prescriptions'
      path: '/doctor/prescriptions'
      fullPath: '/doctor/prescriptions'
      preLoaderRoute: typeof DoctorPrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/profile': {
      id: '/doctor/profile'
      path: '/doctor/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/referral': {
      id: '/doctor/referral'
      path: '/doctor/referral'
      fullPath: '/doctor/referral'
      preLoaderRoute: typeof DoctorReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicines/add': {
      id: '/medicines/add'
      path: '/add'
      fullPath: '/medicines/add'
      preLoaderRoute: typeof MedicinesAddRouteImport
      parentRoute: typeof MedicinesRoute
    }
    '/symptoms/trends': {
      id: '/symptoms/trends'
      path: '/trends'
      fullPath: '/symptoms/trends'
      preLoaderRoute: typeof SymptomsTrendsRouteImport
      parentRoute: typeof SymptomsRoute
    }
  }
}

interface MedicinesRouteChildren {
  MedicinesAddRoute: typeof MedicinesAddRoute
}

const MedicinesRouteChildren: MedicinesRouteChildren = {
  MedicinesAddRoute: MedicinesAddRoute,
}

const MedicinesRouteWithChildren = MedicinesRoute._addFileChildren(
  MedicinesRouteChildren,
)

interface SymptomsRouteChildren {
  SymptomsTrendsRoute: typeof SymptomsTrendsRoute
}

const SymptomsRouteChildren: SymptomsRouteChildren = {
  SymptomsTrendsRoute: SymptomsTrendsRoute,
}

const SymptomsRouteWithChildren = SymptomsRoute._addFileChildren(
  SymptomsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzingRoute: AnalyzingRoute,
  AppointmentsRoute: AppointmentsRoute,
  AssistantRoute: AssistantRoute,
  ChatRoute: ChatRoute,
  CompareRoute: CompareRoute,
  EmergencyRoute: EmergencyRoute,
  FamilyRoute: FamilyRoute,
  HomeRoute: HomeRoute,
  InsuranceRoute: InsuranceRoute,
  LabBookingRoute: LabBookingRoute,
  LoginRoute: LoginRoute,
  MedicinesRoute: MedicinesRouteWithChildren,
  PharmacyRoute: PharmacyRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  ResultsRoute: ResultsRoute,
  SymptomsRoute: SymptomsRouteWithChildren,
  UploadRoute: UploadRoute,
  DoctorAnalyticsRoute: DoctorAnalyticsRoute,
  DoctorClinicRoute: DoctorClinicRoute,
  DoctorCmeRoute: DoctorCmeRoute,
  DoctorDashboardRoute: DoctorDashboardRoute,
  DoctorMessagesRoute: DoctorMessagesRoute,
  DoctorPatientRoute: DoctorPatientRoute,
  DoctorPatientsRoute: DoctorPatientsRoute,
  DoctorPrescriptionsRoute: DoctorPrescriptionsRoute,
  DoctorProfileRoute: DoctorProfileRoute,
  DoctorReferralRoute: DoctorReferralRoute,
  DoctorIndexRoute: DoctorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
